# Generated by Django 2.2.2 on 2019-07-05 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptual_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Level'),
        ),
        migrations.AddField(
            model_name='concept',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conceptual_map.Concept'),
        ),
    ]
