# Generated by Django 2.2.2 on 2019-07-05 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptual_map', '0002_auto_20190705_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conceptual_map.Concept'),
        ),
    ]
