# Generated by Django 2.2.2 on 2019-07-05 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptual_map', '0003_auto_20190705_0337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concept',
            old_name='name',
            new_name='content',
        ),
    ]
