# Generated by Django 2.2.2 on 2019-07-05 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conceptual_map', '0004_auto_20190705_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConcept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='conceptual_map.Concept')),
                ('user', models.ForeignKey(on_delete=False, related_name='concepts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
